name: QUICK CI PIPELINE
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.0.x'
        - name: Restore dependencies
          run: dotnet restore OrderProcessingApp.sln
        - name: Build
          run: dotnet build OrderProcessingApp.sln --no-restore
        - name: Test
          run: dotnet test OrderProcessingApp.sln --no-build --verbosity normal
        - name: Publish
          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          run: dotnet publish OrderProcessingApp.sln -c Release -o ./publish
        - name: Upload Artifact
          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          uses: actions/upload-artifact@v3
          with:
            name: OrderProcessingApp
            path: ./publish/